name: AndroidCI

on:
  push:
    branches: [master]
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Make gradlew executable
        run: cd android && chmod +x ./gradlew
      - name: Build Android Release
        run: |
          cd android && ./gradlew app:assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
